### ISSUE TITLE
Some issue with color codes and "%"

### ISSUE THREAD

**Issue by noftaly** [AyhamAl-Ali/Sk-ST3#1]
Hi,
I'm having some issue with the syntax : 
Some color codes may not work if you have many "%" in one line

```vb
TitleGUIList: &aList &7(page &f%{_p}%&7/&f%{_mp}%&7)
```
Exemple here : every color codes after the %{_p}% will not appear correctly
![image](https://user-images.githubusercontent.com/34779161/50043033-6526fd00-006d-11e9-9e9e-afebd73a86ca.png)

I'm using v2.0
Thanks !

**Comment by AyhamAl-Ali** [comment]
Hey,

Thanks for reporting this.. I will fix that and update it ASAP.
