### ISSUE TITLE
Makes other files grey when turned on instead of color formating. CSS, HTML, JS

### ISSUE THREAD

**Issue by ItzDepstRT** [AyhamAl-Ali/Sk-ST3#13]
https://user-images.githubusercontent.com/77269898/163800259-67b5c806-f764-436a-a2bf-3bc2d5116a0f.mp4

**Comment by AyhamAl-Ali** [comment]
Thank you f or reporting, yes this is a known issue and it's due to the naming used for the grammers, this extension should get a fair recode for the grammar names to not affect other files
