### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by gagaos** [AyhamAl-Ali/Sk-ST3#14]
Hello your plugin for VScode looks great but the autocompletion doesn't work with me.
Please explain how it works.
(Thanks in advance for your answer)
![image_2022-08-15_172901283](https://user-images.githubusercontent.com/83508369/184665433-d10c50bc-445a-4d73-bc70-2003678110cc.png)

**Comment by AyhamAl-Ali** [comment]
Hello,

Thank you :) Unfortunately the extension doesn't support auto completion, only syntax highlighting

**Comment by gagaos** [comment]
Thank you very much for your answer. (do you know a plugin that supports it? Or how else to enable autocompletion)

Thank you for your reply!!!

PS: But I'll come back to you when yours is ready !!!

**Comment by AyhamAl-Ali** [comment]
You're welcome and will be happy to see you use Sk-VSC soon :D

Probably all the current Skript extensions are not outdated but I know this one that should have auto-completion 
![image](https://user-images.githubusercontent.com/20037329/184723612-fed5b915-9187-4a54-948f-dcd481139477.png)

**Comment by gagaos** [comment]
Thank you very much for your answer. (do you know a plugin that supports it? Or how else to enable autocompletion)

Thank you for your reply!!!

PS: But I'll come back to you when yours is ready!!!

**Comment by gagaos** [comment]
Thanks a lot
