### ISSUE TITLE
Disable syntax if there is character before or after

### ISSUE THREAD

**Issue by noftaly** [AyhamAl-Ali/Sk-ST3#2]
Hi,
Please disable the syntax if a "word" is surrounded by characters. 
Examples : 
![image](https://user-images.githubusercontent.com/34779161/50043054-cbac1b00-006d-11e9-9234-08d97689c614.png)

I clearly don't want the "if" to be colored here ;)

I'm using v2.0
Thanks !

**Comment by AyhamAl-Ali** [comment]
Hey,

Thanks for reporting this.. I will fix that and update it ASAP.
